# Generated by Django 2.1.7 on 2019-03-19 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 15, 14, 47, 260089, tzinfo=utc), verbose_name='Created Date'),
        ),
    ]
