# Generated by Django 2.1.7 on 2019-03-20 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_auto_20190319_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='View Count'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 10, 17, 49, 82477, tzinfo=utc), verbose_name='Created Date'),
        ),
    ]
